on: [push]

jobs:
  build:
    name: Build
    runs-on: macos-11
    strategy:
      fail-fast: false
    steps:
      - name: Test clang
        run: |
          export ANDROID_SDK=$ANDROID_HOME
          ls -l $ANDROID_SDK
          export ANDROID_NDK=$ANDROID_HOME/ndk
          ls -l $ANDROID_NDK
          export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/darwin-x86_64
          ls -l $TOOLCHAIN
          export CLANG=$TOOLCHAIN/bin/clang
          $CLANG --version

  build-win:
    runs-on: windows-2019
    if: ${{ false }}  # disable for now
    name: A job to test an action on Windows
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: edit file
        run: echo '' >> README.md && echo VENDOR=Gluon >> README.md
        
      - name: Archive distribution
        uses: actions/upload-artifact@v2
        with:
          name: README.md
          path: README.md

  build-mac:
    runs-on: macos-latest
    if: ${{ false }}  # disable for now
    name: A job to test an action
    steps:
      - name: Setup GraalVM action step0
        uses: jperedadnr/setup-graalvm@release22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup GraalVM action step1
        uses: jperedadnr/setup-graalvm@release22
        with:
          graalvm: '22.0.0.2-Final'
          jdk: 'java17'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup GraalVM action step2
        uses: jperedadnr/setup-graalvm@release22
        with:
          graalvm: '22.0.0-dev-20220126_1053'
          jdk: 'java17'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup GraalVM action step3
        uses: jperedadnr/setup-graalvm@release22
        with:
          graalvm: '21.2.0-dev-20210621_1207'
          jdk: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
