# on: [push]
on:
  workflow_dispatch:
    inputs:
      candidate:
        type: choice
        description: Choose a candidate
        options:
          - RC
          - GA
      rc_version:
        type: string
        default: ''
        description: 'If candidate is RC, set a version like RC1 or RC2, else leave it empty'


jobs:
  precheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Set environment
        shell: bash
        run: |
          PROJECT_VERSION='24.0.0'
          APP_VERSION=$PROJECT_VERSION
          S3_PATH=$PROJECT_VERSION
          CANDIDATE=${{ github.event.inputs.candidate }}
          if [[ "$CANDIDATE" == RC ]]; then
              RC_VERSION=${{ github.event.inputs.rc_version }}
              if [[ "$RC_VERSION" == "" ]]; then
                RC_VERSION="RC"
              fi
              PROJECT_VERSION=${PROJECT_VERSION}-${RC_VERSION}
              S3_PATH=RC/$PROJECT_VERSION
          fi
          echo "Releasing.. "$PROJECT_VERSION
          echo APP_VERSION=$APP_VERSION >> $GITHUB_OUTPUT
          echo PROJECT_VERSION=$PROJECT_VERSION >> $GITHUB_OUTPUT
          echo S3_PATH=$S3_PATH >> $GITHUB_OUTPUT

  build:
    name: Test
    if: ${{ false }}  # disable for now
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup java
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 19

      - name: test
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            export DISPLAY=:90
            Xvfb -ac :90 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          fi
          mvn test

  build-linux:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ false }}  # disable for now
    steps:
      - uses: actions/checkout@v2

      - name: Check content0
        run: ls -l ./src/main/resources
        
      - name: Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}
          
      - name: Make staging directory
        run: mkdir staging

      - name: Copy packages to staging
        run: cp -r src/main/resources/gluonmobile.* staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging          

  build-win:
    runs-on: windows-2019
    if: ${{ false }}  # disable for now
    name: A job to test an action on Windows
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: edit file
        run: echo '' >> README.md && echo VENDOR=Gluon >> README.md
        
      - name: Archive distribution
        uses: actions/upload-artifact@v2
        with:
          name: README.md
          path: README.md

  build-mac:
    runs-on: macos-latest
    if: ${{ false }}  # disable for now
    name: A job to test an action
    steps:
      - name: Setup GraalVM action step0
        uses: jperedadnr/setup-graalvm@release22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup GraalVM action step1
        uses: jperedadnr/setup-graalvm@release22
        with:
          graalvm: '22.0.0.2-Final'
          jdk: 'java17'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup GraalVM action step2
        uses: jperedadnr/setup-graalvm@release22
        with:
          graalvm: '22.0.0-dev-20220126_1053'
          jdk: 'java17'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup GraalVM action step3
        uses: jperedadnr/setup-graalvm@release22
        with:
          graalvm: '21.2.0-dev-20210621_1207'
          jdk: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
